service: dynamodb-nodejs-functions
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  versionFunctions: false
functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: /api
          method: get
